Refactored Scribble tool
sweat-tek/SB-MAI-E20-3 pull request #52
Opened 2020-10-30 09:19 UTC by Denmads

2020-11-13 16:29 UTC, do-nat requested changes
There's a second pipeline file and some duplicated lines of code

2020-11-13 16:29 UTC, do-nat commented on .github/workflows/ci.yml
> +        run: mvn -B package --file JHotDraw/pom.xml
There's already a pipeline in the master. It would be better if you removed this file and pulled the one from master.

2020-11-13 16:29 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/geom/generalpathstrategy/GeneralPathStrategyMultiplePoints.java
> +                                (float) current.x[0], (float) current.y[0]);
Duplicated in lines 50 - 74

2020-11-16 06:29 UTC, Denmads commented
Completed the requested changes

2020-11-16 14:23 UTC, do-nat approved these changes
Seems good now! Nice work with the factory. Maybe in the future separate the refactoring from the tests (only if you did the refactoring before the tests, otherwise very nice like this!)

2020-11-20 11:46 UTC, merged