Align palette - Refactoring & Unit tests
sweat-tek/SB-MAI-E20-3 pull request #62
Opened 2020-11-16 14:31 UTC by TurtlePriest

2020-11-17 13:03 UTC, do-nat requested changes

2020-11-17 13:03 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/samples/svg/gui/AlignToolBar.java
> +        return p;
is this method called somewehere?

2020-11-17 13:03 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/samples/svg/gui/AlignToolBar.java
> +    ResourceBundleUtil labels = ResourceBundleUtil.getBundle("org.jhotdraw.samples.svg.Labels");
labels are only used for initialization, maybe undo to the move to a field but leave it in the constructor

2020-11-17 13:03 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/samples/svg/gui/AlignToolBar.java
> +    }
why are these methods public? It was protected before, why did you make it public?

2020-11-17 13:10 UTC, TurtlePriest commented on JHotDraw/src/main/java/org/jhotdraw/samples/svg/gui/AlignToolBar.java
> +        return p;
Yes! I use it for testing ;)

2020-11-17 13:15 UTC, TurtlePriest commented on JHotDraw/src/test/java/TestSuites/AlignQueueTestSuite.java
> +public class AlignQueueTestSuite {
Yeah, it's just a suite that runs all my test files. Not necessary at all though :P
Should i just remove it?

2020-11-17 13:29 UTC, TurtlePriest commented on JHotDraw/src/main/java/org/jhotdraw/samples/svg/gui/AlignToolBar.java
> +    }
Yeah, i looked into doing that, but wouldn't it become a large and messy method?

2020-11-17 13:37 UTC, TurtlePriest commented on JHotDraw/src/main/java/org/jhotdraw/samples/svg/gui/AlignToolBar.java
> +        return p;
I just realized i could make it protected, and acess it directly. I'll be removing that method

2020-11-17 14:58 UTC, TurtlePriest commented on JHotDraw/src/main/java/org/jhotdraw/samples/svg/gui/AlignToolBar.java
> +    ResourceBundleUtil labels = ResourceBundleUtil.getBundle("org.jhotdraw.samples.svg.Labels");
Not entirely sure what you mean here

2020-11-18 08:50 UTC, TurtlePriest commented
I think i've resolved all your requests, but the consolidation of the methods

2020-11-19 18:58 UTC, xmimmer approved these changes
Looks fine after the refactorings you made suggested by donat.

2020-11-22 06:43 UTC, do-nat approved these changes
Looks better 🙃

2020-11-22 09:45 UTC, merged