Undo redo
sweat-tek/SB-MAI-E20-3 pull request #75
Opened 2020-11-20 18:49 UTC by RichardNemcovic

Feature UndoRedo refactored and tested

2020-11-22 06:58 UTC, do-nat requested changes
The tests are failing (has to be fixed) and the pipeline has to removed. Furthermore, I have some questions regarding some sections of the code 😅

2020-11-22 06:58 UTC, do-nat commented on .github/workflows/build_test_pipeline.yml
> +name: Build code base
there's already _two_ pipelines in the repository, please delete this file 😃

2020-11-22 06:58 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/draw/WhenUndoActionIsPerformed.java
> +        List <Figure> list = argumentList.svgBezierFigure.getDrawing().getChildren();
is not used anymore, can be deleted

2020-11-22 06:58 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/samples/svg/figures/EllipseToolDrawAcceptanceTest.java
> +    public Scenario<GivenMousePressedAndDragged, WhenMouseIsReleased, ThenAnEllipseIsDrawn> getScenario() {
what is the purpose of this method?

2020-11-22 06:58 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/samples/svg/gui/CanvasToolBarTest.java
> +    public Scenario<GivenCanvasToolBar, WhenCanvasToolBar, ThenCanvasToolBar> getScenario() {
what is the purpose?

2020-11-22 06:58 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/undo/UndoRedoManagerTest.java
> +    public void undoOrRedoTest_other(){
I think you should not catch an exception in a test. Look at this:
https://www.baeldung.com/junit-assert-exception

2020-11-27 07:45 UTC, do-nat requested changes

2020-11-27 07:45 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
> +
can be removed

2020-11-27 07:45 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
> +    //TODO remove code smell (Speculative Generality)
commented code should be removed

2020-12-17 13:19 UTC, closed without merging

2020-12-17 13:20 UTC, RichardNemcovic commented
Worked on other branch and creating a new pull request