Undo redo
sweat-tek/SB-MAI-E20-3 pull request #88
Opened 2020-12-17 13:24 UTC by RichardNemcovic

Resolved failing tests of other branches in order to be able to build the project again and pass the pipeline tests.

2021-01-25 19:38 UTC, do-nat requested changes
there's still some things to be done :blush:

2021-01-25 19:38 UTC, do-nat commented on .github/workflows/build_verify_pipeline.yml
> +        run: mvn -B test --file JHotDraw/pom.xml
there is already a pipeline file and this file should not be duplicated in the master branch

2021-01-25 19:38 UTC, do-nat commented on .github/workflows/build_verify_pipeline.yml
> +      - UndoRedo
there's no use in limiting the builds on branches here. You should maybe look up what this implicated :)

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/undo/UndoRedoManagerTest.java
> +        }
what does this do? does this make sense?

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/undo/UndoRedoManagerTest.java
> +        assertEquals(action, UndoRedoManager.UndoRedoAction.UNDO);
these tests seem to test the return value of the method undoOrRedo(). Do they actually do more than that?

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/samples/svg/gui/CanvasToolBarTest.java
>  package org.jhotdraw.samples.svg.gui;
this test works in master, you don't have to adjust it (revert these changes!)

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/samples/svg/figures/EllipseToolDrawAcceptanceTest.java
>   */
this test works on master, you can revert your changes

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/draw/action/SendToBackActionTest.java
>      @Test
this test works on master, you can revert your changes

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/draw/action/BringToFrontActionTest.java
>          String expResult = "edit.bringToFront";
this test works on master, you can revert your changes

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/draw/WhenUndoActionIsPerformed.java
> +        List <Figure> list = argumentList.svgBezierFigure.getDrawing().getChildren();
you don't use this anymore

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/test/java/org/jhotdraw/draw/WhenUndoActionIsPerformed.java
> +    private HashMap<AttributeKey, Object> map;
this does not have to be a property, can be a simple variable

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
>      public void addPropertyChangeListener(String propertyName, PropertyChangeListener listener) {
remove commented code

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
> +
these can be removed (also, these formatting changes in this file should be avoided!)

2021-01-25 19:38 UTC, do-nat commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
> +        //firePropertyChange("hasSignificantEdits", oldValue, newValue);
remove line

2021-01-28 14:40 UTC, RichardNemcovic commented on .github/workflows/build_verify_pipeline.yml
> +        run: mvn -B test --file JHotDraw/pom.xml
Thanks for the information, I removed the other one.

2021-01-28 14:42 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/undo/UndoRedoManagerTest.java
> +        assertEquals(action, UndoRedoManager.UndoRedoAction.UNDO);
These test check, if there was an appropriate workflow, based on precondtions

2021-01-28 14:46 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/samples/svg/gui/CanvasToolBarTest.java
>  package org.jhotdraw.samples.svg.gui;
Done

2021-01-28 14:47 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/samples/svg/figures/EllipseToolDrawAcceptanceTest.java
>   */
done

2021-01-28 14:48 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/draw/action/SendToBackActionTest.java
>      @Test
done

2021-01-28 14:49 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/draw/action/BringToFrontActionTest.java
>          String expResult = "edit.bringToFront";
done

2021-01-28 14:50 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/draw/WhenUndoActionIsPerformed.java
> +        List <Figure> list = argumentList.svgBezierFigure.getDrawing().getChildren();
deleted

2021-01-28 14:52 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/draw/WhenUndoActionIsPerformed.java
> +    private HashMap<AttributeKey, Object> map;
True, done

2021-01-28 14:53 UTC, RichardNemcovic commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
>      public void addPropertyChangeListener(String propertyName, PropertyChangeListener listener) {
done

2021-01-28 14:54 UTC, RichardNemcovic commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
> +
done

2021-01-28 14:54 UTC, RichardNemcovic commented on JHotDraw/src/main/java/org/jhotdraw/undo/UndoRedoManager.java
> +        //firePropertyChange("hasSignificantEdits", oldValue, newValue);
done

2021-01-28 14:55 UTC, RichardNemcovic commented on .github/workflows/build_verify_pipeline.yml
> +        run: mvn -B test --file JHotDraw/pom.xml
done

2021-01-28 14:56 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/undo/UndoRedoManagerTest.java
> +        assertEquals(action, UndoRedoManager.UndoRedoAction.UNDO);
They check the correctness of the workflow, but apart from that no.

2021-01-28 14:56 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/samples/svg/gui/CanvasToolBarTest.java
>  package org.jhotdraw.samples.svg.gui;
done

2021-01-28 14:58 UTC, RichardNemcovic commented on JHotDraw/src/test/java/org/jhotdraw/undo/UndoRedoManagerTest.java
> +        }
Yes, the "undoRedoManager.undoOrRedo(UndoRedoManager.UndoRedoAction.TEST);" should throw an error and if not, the test should fail. If it throws, it just prints out the error message.

2021-01-28 15:42 UTC, do-nat approved these changes

2021-01-28 15:45 UTC, merged